config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :comments
  resources :publishes do
    collection do
      post 'likes/:id', to: 'publishes#likes_publish', as: :likes
      get 'user_publish/:id', to: 'publishes#user_publish', as: :user_publish
    end
  end
  # devise_for :users, :controllers => { registrations: 'registrations' }
  

  root to: 'publishes#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb

class Comment < ApplicationRecord
    belongs_to :publish
    belongs_to :user


    
#>>>>>>>>>>>>>>>>>>>>paginacion<<<<<<<<<<<<<<<<<<<<<<<
paginates_per 2
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


has_rich_text :body

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :auth_user

  # GET /comments or /comments.json
  def index
    @comments = Comment.where("user_id = #{current_user.id}").page params[:page]
    @publish = Publish.where("id = #{@comments.first.id}").page params[:page]
  end

  # GET /comments/1 or /comments/1.json
  def show
    @publicacion = Publish.where("id = #{@comment.id}").page params[:page]
    @publish = Publish.where("id = #{@comment.id}").page params[:page]
  end

  # GET /comments/new
  def new
    @publicacion = Publish.where("id = #{params[:format]}")
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.publish_id = comment_params[:publish_id]
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "El comentario fue creado con éxito." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "El comentario ha sido eliminado." }
      format.json { head :no_content }
    end
  end

  private 

  def auth_user
    if !user_signed_in?
        redirect_to root_path
        flash[:alert] = "Debes iniciar Sesion"
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      #  binding.break
      params.require(:comment).permit(:commenter, :body, :publish_id)
    end
end


app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card"  id="card-comment1">
  <div id="<%= dom_id comment %>">
  <p><strong>Publicacion:</strong></p>
  <% if !@publish.blank?  %>
    <p><%= @publish.first.title.capitalize %></p><br>
  <% end %>
    <p><strong>Tu comentario:</strong></p>
    <p><%= comment.body%></p>
  </div>
</div>


app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="card" id="card-comment">
  <div class="card-body">
  <h4 class="card-title mb-3">Aporta tu Comentario</h4>
  <div>
    <%# <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body, class:"form-control", id:"comment" %>
    <% if !@publicacion.blank? %>
    <%= form.hidden_field :publish_id, value: @publicacion.first.id %>
    <% end %>
  </div>
  <div class="mt-3">
    <p><%= form.submit  class: 'btn btn-warning', id:'btnComentari', value:'Guardar' %></p>
    <a href="/">Regresar a incio</a>
    <%# <%= link_to "Regresar a incio", comments_path, id:"regresar" %>
  </div>
</div>
 </div> 
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb

<h1>Comentarios</h1>
<br>
<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Ver Comentario", comment %>
    </p>
  <% end %>
</div>
<div class="paginate">
  <%= paginate @comments, id:'paginate'%>
</div>     


app/views/comments/new.html.erb
<%= render "form", comment: @comment %>
<br>


app/views/comments/show.html.erb
<%# <p style="color: green"><%= notice %>

<%# <div class="card"  id="card-comment1"> %>
  <%# <div >
    <p><strong>Publicación:</strong></p>
    <%# <p><%= @publicacion.first.title %></p>
  <%# </div> %>
<%# </div> %>

<%= render @comment %>
<% if current_user.id == @comment.user_id %>
<div>
  <%= link_to "Editar este comentario", edit_comment_path(@comment) %> |
  <%= link_to "Regresar a comentarios", comments_path %>
  <%= button_to "Eliminar comentario", @comment, method: :delete, class: 'btn btn-warning', id:'btnComentari' %>
</div>
<% end %>