config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :comments
  resources :publishes do
    collection do
      post 'likes/:id', to: 'publishes#likes_publish', as: :likes
      get 'user_publish/:id', to: 'publishes#user_publish', as: :user_publish
    end
  end
  # devise_for :users, :controllers => { registrations: 'registrations' }
  

  root to: 'publishes#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/publish.rb
class Publish < ApplicationRecord


#>>>>>>>>>>>>>>validaciones<<<<<<<<<<<<<<<<<<<
validates :title, presence: true, length: {minimum:3, maximum:55}
validates :content, presence: true
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#>>>>>>>>>>>>>>>Asociacciones/Relaciones<<<<<<<<<<<<<<<<<
has_many :comment
belongs_to :user
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

has_rich_text :content

has_one_attached :content


#>>>>>>>>>>>>>>Scopes<<<<<<<<<<<<<<<<<<

scope :search_content, ->(search){ where("content LIKE ? or title LIKE ?", "%"+search+"%","%"+search+"%" ).order("created_at DESC") }
scope :more_likes, ->(){ order("likes DESC").limit(10) }

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


#>>>>>>>>>>>>>>>>>>>>paginacion<<<<<<<<<<<<<<<<<<<<<<<
paginates_per 2
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


    def counterLikes(id)
        where_str = "id = #{id}"
        count_likes = Publish.select(:likes).where(where_str)
            count_likes.each do |lk|
                count = lk.likes.to_i 
                return count += 1
            end
    end

    def counterdislikes(id)
        where_str = "id = #{id}"
        count_likes = Publish.select(:dislikes).where(where_str)
            count_likes.each do |lk|
                count = lk.dislikes.to_i 
                return count += 1
            end
    end

    
end


app/controllers/publishes_controller.rb
class PublishesController < ApplicationController
  before_action :set_publish, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except:[:index, :likes_publish]

  # GET /publishes or /publishes.json
  def index
    if !params[:search].blank?
      q = params[:search]
      @publishes =  Publish.order("published_at DESC").search_content(q).page params[:page] 
        if @publishes.size > 0
           @publishes
           @more_likes = Publish.more_likes
           @total_publish = Publish.all
        else
          flash.now[:alert] = "No se encontraron coincidencias con la palabra: #{q}"
          @publishes = Publish.order("published_at DESC").page params[:page] 
          @more_likes = Publish.more_likes
          @total_publish = Publish.all
        end  
      else
        @publishes = Publish.order("published_at DESC").page params[:page]
        @more_likes = Publish.more_likes
        @total_publish = Publish.all
    end
  end

  def user_publish
        @publishes = Publish.where("user_id = #{params[:id]}").page params[:page]
  end
  

  # GET /publishes/1 or /publishes/1.json
  def show
    @comentarios = Comment.where(publish_id: @publish.id ).page params[:page]
  end

  # GET /publishes/new
  def new
    @publish = Publish.new
  end

  # GET /publishes/1/edit
  def edit
  end

  # POST /publishes or /publishes.json
  def create
    @publish = Publish.new(publish_params)
    #binding.break
    @publish.user_id = current_user.id
    @publish.published_at = Time.now
    respond_to do |format|
      if @publish.save
        format.html { redirect_to publish_url(@publish), notice: "La publicación se creó con éxito." }
        format.json { render :show, status: :created, location: @publish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishes/1 or /publishes/1.json
  def update
    respond_to do |format|
      if @publish.update(publish_params)
        format.html { redirect_to publish_url(@publish), notice: "Publish was successfully updated." }
        format.json { render :show, status: :ok, location: @publish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishes/1 or /publishes/1.json
  def destroy
    @publish.destroy

    respond_to do |format|
      format.html { redirect_to publishes_url, notice: "La publicacion fue eliminada con éxito." }
      format.json { head :no_content }
    end
  end

  def likes_publish
    publish = Publish.find(params[:id])
    publish.likes = publish.counterLikes(params[:id]) if params[:format] == "likes"
    publish.dislikes = publish.counterdislikes(params[:id]) if params[:format] == "dislikes"
    publish.save(validate: false)
    #redirect_to '/publishes'
    redirect_back(fallback_location: { action: "index", id: publish.id})
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publish
      @publish = Publish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publish_params
      params.require(:publish).permit(:title, :content, :likes, :dislikes)
    end
end

app/helpers/publishes_helper.rb
module PublishesHelper
end

app/views/publishes/_form.html.erb
<%= form_with(model: publish) do |form| %>
  <% if publish.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publish.errors.count, "error") %> prohibited this publish from being saved:</h2>

      <ul>
        <% publish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row" id="title-question">
    <h2>Cuál es tu pregunta?</h2>
  </div>
  <div class="row" id="input-title">
    <%# <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control"%>
    <div id="info-question" class="form-text">Especifique su pregunta de forma clara</div>
  </div>

  <div class="row" id="input-content">
    <%# <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content, class:"form-control" %>
    <div id="info-body" class="form-text">Incluye toda la información necesaria para respoder tu pregunta</div>
  </div>

  <div class="row">
    <%= form.submit class:"btn btn-warning", value:'Guardar' %>
  </div>
  <div class="row" id="back-question">
  <%= link_to "Regresar a inicio", publishes_path %>
  </div>
<% end %>

app/views/publishes/_publish.html.erb
<div class="card" id="container-publishes">
  <div class="card-body">
    <div id="<%= dom_id publish %>">
      <p><%= link_to "#{publish.title.capitalize}", publish, id:'title_publish' %></p>
      <div class="body_publish">
      <p><%= publish.content%></p>
      </div>
      <hr>      
      <p id="create"><strong>Fecha publicacion:</strong> <%= publish.published_at.to_s.to_date%></p>
      <p id="create"><strong>Creado por:</strong> <%= !publish.user.nickname.blank? ? publish.user.nickname.capitalize : "Anonimo"  %></p>
      <p id="create"><strong>comentarios:</strong> <%= publish.comment.where(:publish_id == publish.id).count  %></p>
      <%= button_to "Aporta tu comentario", new_comment_path(publish.id), method: "get",  class: 'btn btn-warning', id:'btnComentari'%>
        <div class="row" id="container-like">
          <div class="col-1" id="btnLike">
            <%= button_to "", likes_publishes_path(publish.id,"likes"), method: "post",  class: 'btn btn-light position-absolute bi bi-emoji-laughing', id:"like"%>
                <span class="position-relative top-0 start-100 translate-middle badge rounded-pill bg-danger">
              <%= publish.likes %>
            </span>
          </div>
        <div class="col-1" id="btnDislike">
          <%= button_to "", likes_publishes_path(publish.id,"dislikes"), method: "post",  class: 'btn btn-light position-absolute bi bi-emoji-dizzy', id:"dislike"%>
          <span class="position-relative top-0 start-100 translate-middle badge rounded-pill bg-danger">
              <%= publish.dislikes %>
          </span>
        </div>                        
      </div>
    </div>    
  </div>
</div>


app/views/publishes/_search.html.erb

  <div id="search" class="buscar">
        <%= form_tag(publishes_path, method: :get) do %>
            <%= text_field_tag(:search, params[:search], placeholder: "Buscar", id:"input" ) %>
            <%= submit_tag (""), id:"btn", class:"btn" %>
                <div id="btn" class="btn">
                    <i  class="bi bi-search"></i>
                </div>
        <% end %>
  </div>

app/views/publishes/edit.html.erb
<h1>Editing publish</h1>

<%= render "form", publish: @publish %>

<br>

<div>
  <%= link_to "Mostrar publicación", @publish %> |
  <%= link_to "Regresar al inicio", publishes_path %>
</div>

app/views/publishes/index.html.erb
<div class="container">
<div class="row">
    <div class="col-md-12">
      <%= render "search" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12" id='btn_filter'> 
    <%= link_to "Formula una pregunta", new_publish_path, class: 'btn btn-secondary box-1', id:'btnQuestion' %>
      <div class="btn-group" role="group">  
        <%# <%= button_to 'Activas', user_session_path, class: 'btn btn-warning box-1', id:'btnActive'%>
        <%# <%= button_to 'Populares', user_session_path, class: 'btn btn-warning box-1', id:'btnPopular'%>
        <%# <button type="button" class="btn btn-warning bi bi-filter box-1" data-bs-toggle="dropdown" aria-expanded="false" id="btnfilter"></button> %>
        <%# <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
          <li><a class="dropdown-item" href="#">Semana</a></li>
          <li><a class="dropdown-item" href="#">Mes</a></li>
          <li><a class="dropdown-item" href="#">Año</a></li>
        </ul>         %>
      </div>      
    </div>
  </div>
  <div class="row" id="container-card">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body" id="card_Pprincipal">
        <h3 class="card-title" id="publish_name">Publicaciones</h3>
        <hr>
          <div class='mt-3  '>
            <div id="publishes">
              <% @publishes.each do |publish| %>
              <%= render publish %>
              <% end %>              
            </div> 
            <div class="paginate">
              <%= paginate @publishes, id:'paginate'%>
            </div>        
          </div>
        </div>  
      </div> 
    </div>
    <div class="col-md-4">
      <div class="card" id="card-votados">
        <div class="card-body">
          <h4 class="card-title"><center><%= @more_likes.size  %> Temas más Valorados</center></h4>
          <hr>
            <div class='mt-3  votadosindex'>
              <% @more_likes.each do |morelikes|  %> 
                    <% total = (morelikes.likes + morelikes.dislikes)  %>
                <div class="card text-bg-light mb-3" style="max-width: 100%;">
                <div class="card-header"><h6><%= morelikes.title.capitalize %></h6></div>
                  <div class="card-body">
                    <p class="card-text" id="create"><strong>Publicado por:</strong>  <%= morelikes.user.nickname.capitalize %> </p>
                    <p class="card-text" id="create"><strong>Valoración: </strong> 
                    <% if total.to_f != 0 || total.to_f < 0 %>
                    <% total_2 = (morelikes.likes.to_f / (total.to_f)) %>
                    <%= (total_2 * 100).to_i%>%                  
                    <% else %>
                      <%= 0 %>%</p>
                    <% end %>
                    <p><%= link_to "Ver", publish_path(morelikes.id) %></p>
                  </div>
                </div>             
              <% end %>
            </div>
        </div>  
      </div>
    </div>
  </div>
</div>







app/views/publishes/new.html.erb
<div class="container" id="container_newP">
  <div class="card" id="new_publish">
    <%= render "form", publish: @publish %>
  </div>
</div>




app/views/publishes/show.html.erb
<%# <p style="color: green"><%= notice %>
<div class="card" id="card-comentari">
<%= render @publish %>

<div>
<% if @publish.user_id == current_user.id %>
    <div class="row" id="btnPublish_id">
      <div class="col-md-2">
        <%= link_to "Editar publicacion", edit_publish_path(@publish), class: 'btn btn-secondary', id:'btnEdit_p' %>
      </div>
      <div class="col-md-2">
        <%= button_to "Eliminar publicacion", @publish, method: :delete, class: 'btn btn-secondary', id:'btnDelete_p' %>
      </div>
       <div class="col-md-2">
          <%= link_to "Regresar", publishes_path, class: 'btn btn-secondary', id:'btnBack_p' %>
       </div>
    </div>   
  <% else  %>
    <div class="row" id="btnPublish_id">
      <%= link_to "Regresar a inicio", publishes_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

<div class="card-body">
  <hr>
    <h4 class="card-title"><center>Comentarios</center></h4>
  <hr>
    <div class='mt-3'>
      <% @comentarios.each do |coments|  %> 
        <div class="card text-bg-light mb-3" style="max-width: 100%;">
            <div class="card-body">
              <p class="card-text"><%= coments.body %></p>
              <p id="create"><strong>Fecha Respuesta:</strong> fecha</p>
              <p id="create"><strong>Creado por:</strong> nick</p>
            </div>
          </div>
      <% end %>
      <%= paginate @comentarios, id:'paginate',  style: "max-width: 100%;" %>
        </div>             
    </div>
</div>
</div>
 



app/views/publishes/user_publish.html.erb
<% @publishes.each do |publish| %>
<div class="card"  id="card-comment1">
  <div>
    <p><strong>Tu publicacion:</strong></p>
    <p><%= publish.title%></p>
  </div>
  <div>
    <p><%= publish.content %></p>
  </div>
</div>

<% if publish.user_id == current_user.id %>
    <div class="row" id="btnPublish_id">
      <div class="col-md-2">
        <%= link_to "Editar publicacion", edit_publish_path(publish.id), class: 'btn btn-secondary', id:'btnEdit_p' %>
      </div>
       <div class="col-md-2">
          <%= link_to "Regresar", publishes_path, class: 'btn btn-secondary', id:'btnBack_p' %>
       </div>
    </div>   
  <% else  %>
    <div class="row" id="btnPublish_id">
      <%= link_to "Regresar a inicio", publishes_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
  <% end %>

  <div class="paginate">
    <%= paginate @publishes, id:'paginate'%>
  </div>    