config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :comments
  resources :publishes do
    collection do
      post 'likes/:id', to: 'publishes#likes_publish', as: :likes
      get 'user_publish/:id', to: 'publishes#user_publish', as: :user_publish
    end
  end
  # devise_for :users, :controllers => { registrations: 'registrations' }
  

  root to: 'publishes#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbarfull.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="btn-group" role="group">
        <% if user_signed_in?  %>
          <a class="btn btn-warning bi bi-list" id="menu" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample"></a>    
        <% end %>
      <a id="name_ucode" href="/">Universal Code</a>
    </div> 
    <%# <div>
      <% if user_signed_in?  %>
        <%# <h5>Hola! <%= current_user.nickname.capitalize %></h5>
      <%# <% end %>
    <%# </div> %>
    <div class="btn-group" role="group">       
      <% if user_signed_in? %>
            <h5 id="nick_perfil">Hola! <%= current_user.nickname.capitalize%></h5> 
            <%# <h5 id="nick_perfil1"><span class="typed"></span></h5>     %>
          <%= button_to '', destroy_user_session_path, method: :delete, form: {data: {turbo_confirm: 'Esta seguro?'}}, class: 'btn btn-light bi bi-door-closed', id:'btnLogout' %>
      <% else  %> 
          <%= button_to '', user_session_path ,  class: 'btn btn-light bi bi-person-fill', id:'btnSign_in' %> 
      <% end %>   
    </div>
  </div>
</nav>

<% if user_signed_in? %>
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
  <%# <button type="button" id="btnClose" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button> %>
    <%= image_tag('logo1', id:'logo_menu') %>
    <h3 class="offcanvas-title"><%= current_user.nickname.capitalize %>
  </div>   
  <div class="offcanvas-body">
    <%# <center><h3></h3></center> %>
    <hr>
    <%# <h3>Mis Publicaciones:</h3> %>
    <div id="content_Mpublics">
      <%= link_to "Mis Publicaciones", user_publish_publishes_path(current_user.id), id:"btnMispiblicaciones" %>
    </div>
    <hr>
    <%# <h3>Mis Comentarios:</h3> %>
    <div id="content_Mcomment">
      <%= link_to "Mis Comentarios", comments_path, id:"btnMiscomment" %>
    </div>
  </div>
  <% end %>
</div>     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ucode</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'logo5' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "styles", :media => "all" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap" rel="stylesheet">
  </head>

  <body>  
<div class="container-body">
   <%= render "layouts/navbarfull" %>  
    <div class="container mt-5">
    <% if !alert.blank? %>
      <div class="row" id="content-alert">
        <div class="alert alert-danger" role="alert" id="alert_danger">
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          <%= alert %>        
        </div>
      </div>
        <% elsif !notice.blank? %>
          <div class="row" id="content-alert">
            <div class="alert alert-warning" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            <%= notice %>
          </div>
      </div>
    <% end %>
      <%= yield %>
    </div>
</div>  
  <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
  <script>
  let nick = document.getElementById("nick_perfil1").innerHTML;
  const typed = new Typed('.typed', {
	strings: [
		'<i class="mascota">'+nick+'</i>'
	],
	//stringsElement: '#cadenas-texto', // ID del elemento que contiene cadenas de texto a mostrar.
	typeSpeed: 75, // Velocidad en mlisegundos para poner una letra,
	startDelay: 300, // Tiempo de retraso en iniciar la animacion. Aplica tambien cuando termina y vuelve a iniciar,
	backSpeed: 75, // Velocidad en milisegundos para borrrar una letra,
	smartBackspace: true, // Eliminar solamente las palabras que sean nuevas en una cadena de texto.
	shuffle: false, // Alterar el orden en el que escribe las palabras.
	backDelay: 1500, // Tiempo de espera despues de que termina de escribir una palabra.
	loop: false, // Repetir el array de strings
	loopCount: false, // Cantidad de veces a repetir el array.  false = infinite
	showCursor: false, // Mostrar cursor palpitanto
	cursorChar: '|', // Caracter para el cursor
	contentType: 'html', // 'html' o 'null' para texto sin formato
});
  </script>
  </body>
</html>